In [ ]:
# ------------ ARRAY CREATION--------------
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
b = np.zeros((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# linspace  tells equally spaced numbers between two numbers 
a = np.linspace(2,20,11)
print(a)

[ 2.   3.8  5.6  7.4  9.2 11.  12.8 14.6 16.4 18.2 20. ]


In [ ]:
# eye gives us identity matrix of n     
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# full array of required order filled with same number
a = np.full((2,3), 3)
print(a)

[[3 3 3]
 [3 3 3]]


In [ ]:
# empty creates null array of required order 
a = np.empty((2,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
#------------------ ARRAY OPERATIONS----------

# adding arrays
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

c = np.add(a,b)
print(c)


# Subtraction arrays
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

c = np.subtract(a,b)
print(c)


# multipling arrays
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

c = np.multiply(a,b)
print(c)


# dividing  arrays
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

c = np.divide(a,b)
print(c)


# square root of each element
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

print(np.sqrt(a))
print(np.sqrt(b))


# powering each element
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

print(np.power(a,2))
print(" ")
print(np.power(b,3))


#mod of each element by 2
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

print(np.mod(a,2))
print(" ")
print(np.mod(b,3))
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

print(np.clip(a,2,5))
print(" ")
print(np.clip(b,1,3))


[[ 3  8  9]
 [ 6  6 10]]
[[ 1  4  7]
 [-2  0 -2]]
[[ 2 12  8]
 [ 8  9 24]]
[[2.         3.         8.        ]
 [0.5        1.         0.66666667]]
[[1.41421356 2.44948974 2.82842712]
 [1.41421356 1.73205081 2.        ]]
[[1.         1.41421356 1.        ]
 [2.         1.73205081 2.44948974]]
[[ 4 36 64]
 [ 4  9 16]]
 
[[  1   8   1]
 [ 64  27 216]]
[[0 0 0]
 [0 1 0]]
 
[[1 2 1]
 [1 0 0]]
[[2 5 5]
 [2 3 4]]
 
[[1 2 1]
 [3 3 3]]


In [3]:
#-------------- STATISTICAL FUNCTIONS -----------#

import numpy as np

# Array
a = np.array([10, 20, 30, 40, 50])

# Mean
print("Mean:", np.mean(a))

# Median
print("Median:", np.median(a))

# Standard Deviation
print("Standard Deviation:", np.std(a))

# Variance
print("Variance:", np.var(a))

# Minimum value
print("Minimum:", np.min(a))

# Maximum value
print("Maximum:", np.max(a))

# Percentile
print("25th Percentile:", np.percentile(a, 25))
print("50th Percentile:", np.percentile(a, 50))

# Average with weights
weights = [1, 2, 3, 4, 5]
print("Weighted Average:", np.average(a, weights=weights))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0
Minimum: 10
Maximum: 50
25th Percentile: 20.0
50th Percentile: 30.0
Weighted Average: 36.666666666666664


In [5]:
#---------------------- Aggregate Functions ----------------#

import numpy as np

# Array
a = np.array([1, 2, 3, 4, 5])

# Sum
print("Sum:", np.sum(a))

# Product
print("Product:", np.prod(a))

# Cumulative Sum
print("Cumulative Sum:", np.cumsum(a))

# Cumulative Product
print("Cumulative Product:", np.cumprod(a))

# Index of Maximum value
print("Index of Max Value:", np.argmax(a))

# Index of Minimum value
print("Index of Min Value:", np.argmin(a))

# Boolean array for all() and any()
b = np.array([True, True, False, True])

# Check if all values are True
print("All True?:", np.all(b))

# Check if any value is True
print("Any True?:", np.any(b))

Sum: 15
Product: 120
Cumulative Sum: [ 1  3  6 10 15]
Cumulative Product: [  1   2   6  24 120]
Index of Max Value: 4
Index of Min Value: 0
All True?: False
Any True?: True


In [6]:
#--------------------Linear Algebra  ------------

import numpy as np

# Matrices
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# Dot Product
print("Dot Product:\n", np.dot(a, b))

# Matrix Multiplication
print("Matrix Multiplication:\n", np.matmul(a, b))

# Inverse of matrix
print("Inverse of a:\n", np.linalg.inv(a))

# Determinant
print("Determinant of a:", np.linalg.det(a))

# Eigenvalues and Eigenvectors
values, vectors = np.linalg.eig(a)
print("Eigenvalues:\n", values)
print("Eigenvectors:\n", vectors)

# Norm
print("Norm of matrix a:", np.linalg.norm(a))

# QR Decomposition
Q, R = np.linalg.qr(a)
print("Q Matrix:\n", Q)
print("R Matrix:\n", R)

# Singular Value Decomposition
U, S, V = np.linalg.svd(a)
print("U Matrix:\n", U)
print("Singular Values:\n", S)
print("V Matrix:\n", V)

Dot Product:
 [[19 22]
 [43 50]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Inverse of a:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of a: -2.0000000000000004
Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Norm of matrix a: 5.477225575051661
Q Matrix:
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R Matrix:
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]
U Matrix:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular Values:
 [5.4649857  0.36596619]
V Matrix:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [7]:
#------------------------Random Operations  ------------

import numpy as np

# Set seed (same random numbers every run)
np.random.seed(1)

# Random numbers between 0 and 1
print("Random numbers [0,1):", np.random.rand(3))

# Random integers
print("Random Integers:", np.random.randint(1, 10, 5))

# Normal distribution
print("Normal Distribution:", np.random.normal(0, 1, 5))

# Random choice from array
a = np.array([10, 20, 30, 40, 50])
print("Random Choice:", np.random.choice(a, 3))

# Shuffle array
b = np.array([1, 2, 3, 4, 5])
np.random.shuffle(b)
print("Shuffled Array:", b)

# Uniform distribution
print("Uniform Distribution:", np.random.uniform(0, 5, 4))

# Poisson distribution
print("Poisson Distribution:", np.random.poisson(3, 5))

Random numbers [0,1): [4.17022005e-01 7.20324493e-01 1.14374817e-04]
Random Integers: [6 1 1 2 8]
Normal Distribution: [-1.10593508 -1.65451545 -2.3634686   1.13534535 -1.01701414]
Random Choice: [30 50 30]
Shuffled Array: [1 3 2 4 5]
Uniform Distribution: [0.70193469 0.99050745 4.00372284 4.84130788]
Poisson Distribution: [4 0 2 4 2]


In [8]:
#---------------------Shape Operations -----------
import numpy as np

# Original array
a = np.array([[1,2,3],
              [4,5,6]])

print("Original Array:\n", a)

# Reshape
print("\nReshape (3x2):\n", np.reshape(a,(3,2)))

# Flatten
print("\nFlatten:", a.flatten())

# Transpose
print("\nTranspose:\n", np.transpose(a))

# Resize
b = np.array([1,2,3,4])
print("\nResize (2x3):\n", np.resize(b,(2,3)))

# Expand dimensions
c = np.array([1,2,3])
print("\nExpand Dims:\n", np.expand_dims(c, axis=0))

# Squeeze
d = np.array([[[1,2,3]]])
print("\nSqueeze:", np.squeeze(d))

# Ravel
print("\nRavel:", a.ravel())

# Horizontal Stack
x = np.array([1,2,3])
y = np.array([4,5,6])
print("\nHorizontal Stack:", np.hstack((x,y)))

# Vertical Stack
print("\nVertical Stack:\n", np.vstack((x,y)))

Original Array:
 [[1 2 3]
 [4 5 6]]

Reshape (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Flatten: [1 2 3 4 5 6]

Transpose:
 [[1 4]
 [2 5]
 [3 6]]

Resize (2x3):
 [[1 2 3]
 [4 1 2]]

Expand Dims:
 [[1 2 3]]

Squeeze: [1 2 3]

Ravel: [1 2 3 4 5 6]

Horizontal Stack: [1 2 3 4 5 6]

Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [9]:
#-------------------------Indexing & Slicing ------------------

import numpy as np

# Array
a = np.array([10, 20, 10, 30, 40, 0, 50])

print("Original Array:", a)

# np.where()
print("\nIndices where value > 20:", np.where(a > 20))

# np.take()
indices = [0, 2, 4]
print("\nTake elements at indices [0,2,4]:", np.take(a, indices))

# np.unique()
print("\nUnique elements:", np.unique(a))

# np.nonzero()
print("\nIndices of non-zero elements:", np.nonzero(a))

# np.argsort()
print("\nIndices that would sort the array:", np.argsort(a))

# np.split()
b = np.array([1,2,3,4,5,6])
print("\nSplit array:", np.split(b, 3))

# np.flip()
print("\nFlipped array:", np.flip(a))

# np.roll()
print("\nRolled array (shift=2):", np.roll(a, 2))

Original Array: [10 20 10 30 40  0 50]

Indices where value > 20: (array([3, 4, 6]),)

Take elements at indices [0,2,4]: [10 10 40]

Unique elements: [ 0 10 20 30 40 50]

Indices of non-zero elements: (array([0, 1, 2, 3, 4, 6]),)

Indices that would sort the array: [5 0 2 1 3 4 6]

Split array: [array([1, 2]), array([3, 4]), array([5, 6])]

Flipped array: [50  0 40 30 10 20 10]

Rolled array (shift=2): [ 0 50 10 20 10 30 40]


In [10]:
#-------------------------Create DataFrame (Pandas) 
import pandas as pd

# Data
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [22, 23, 21],
    "City": ["Lahore", "Karachi", "Islamabad"]
}

# Create DataFrame
df = pd.DataFrame(data)
print("DataFrame:\n", df)

# Create Series
s = pd.Series([10, 20, 30, 40])
print("\nSeries:\n", s)

# DataFrame from dictionary
df2 = pd.DataFrame.from_dict(data)
print("\nDataFrame from Dict:\n", df2)

# Read CSV
print("\nRead CSV:")
print(pd.read_csv("data.csv"))

# Read Excel
print("\nRead Excel:")
print(pd.read_excel("data.xlsx"))

# Read JSON
print("\nRead JSON:")
print(pd.read_json("data.json"))

# Read SQL
print("\nRead SQL:")
print(pd.read_sql("SELECT * FROM students", connection))

# Read HTML
print("\nRead HTML:")
print(pd.read_html("https://example.com"))

DataFrame:
     Name  Age       City
0    Ali   22     Lahore
1   Sara   23    Karachi
2  Ahmed   21  Islamabad

Series:
 0    10
1    20
2    30
3    40
dtype: int64

DataFrame from Dict:
     Name  Age       City
0    Ali   22     Lahore
1   Sara   23    Karachi
2  Ahmed   21  Islamabad

Read CSV:


FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [ ]:
#--------------------