In [ ]:
# adding arrays
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

c = np.add(a,b)
print(c)

[[ 3  8  9]
 [ 6  6 10]]


In [ ]:
# Subtraction arrays
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

c = np.subtract(a,b)
print(c)

[[ 1  4  7]
 [-2  0 -2]]


In [ ]:
# multipling arrays
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

c = np.multiply(a,b)
print(c)

[[ 2 12  8]
 [ 8  9 24]]


In [ ]:
# dividing  arrays
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

c = np.divide(a,b)
print(c)

[[2.         3.         8.        ]
 [0.5        1.         0.66666667]]


In [9]:
# square root of each element
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

print(np.sqrt(a))
print(np.sqrt(b))

[[1.41421356 2.44948974 2.82842712]
 [1.41421356 1.73205081 2.        ]]
[[1.         1.41421356 1.        ]
 [2.         1.73205081 2.44948974]]


In [ ]:
# powering each element
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

print(np.power(a,2))
print(" ")
print(np.power(b,3))

[[ 4 36 64]
 [ 4  9 16]]
 
[[  1   8   1]
 [ 64  27 216]]


In [14]:
#mod of each element by 2
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

print(np.mod(a,2))
print(" ")
print(np.mod(b,3))

[[0 0 0]
 [0 1 0]]
 
[[1 2 1]
 [1 0 0]]


In [15]:
import numpy as np
a = np.array([[2,6,8],
              [2,3,4,]])
b = np.array([[1,2,1],
              [4,3,6]])

print(np.clip(a,2,5))
print(" ")
print(np.clip(b,1,3))

[[2 5 5]
 [2 3 4]]
 
[[1 2 1]
 [3 3 3]]
